spring:
    application:
        name: Cafe
    datasource:
        url: jdbc:postgresql://dpg-d0ks1abe5dus73c22ae0-a.oregon-postgres.render.com:5432/cafeappdb?sslmode=require
        driver-class-name: org.postgresql.Driver
        username: cafeappdb_user
        password: ymMfDniAqONsAjoxh5AlnfB1JSuZJLio
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
    sql:
        init:
            data-locations: classpath:init.sql
#            mode: always
server:
    port: 8080
front-url: https://telegramcafefront.onrender.com
jwt:
    secret: "6904bbfd6566d0adc879a0f132f379c1ada24116bfde995ecb1a5495b5f4e31a"
    access-expire: "43200000"
    refresh-expire: "25200000"